### ISSUE TITLE
Unable to compile/build/run 

### ISSUE THREAD

**Issue by yazoo178** [Davipb/jamspell-java#1]
Hello,

I am confused as to what I need to do to build this repo to use it as part of my Java project.

I am working on a 64 bit Linux Ubuntu server.

Thanks

**Comment by Davipb** [comment]
Hey there,

If you just want to use the project with no modifications, you can download a pre-compiled .jar on the [releases page](https://github.com/Davipb/jamspell-java/releases/tag/v0.1.0).

To build the project from source you need to clone the repo, navigate to the `java` folder, and run `./gradlew build` (you might have to `chmod +x gradlew` first). If everything goes well, the .jar should be generated in the `build/libs` folder.

**Comment by yazoo178** [comment]
Great! Thanks!
